table 'fact_iam_policy (3)'
	lineageTag: c5c6d58d-72ef-43c6-b4eb-90254b5bcb16

	column 'Project ID'
		dataType: string
		lineageTag: 08d19d4b-cdb5-46d2-8a7c-fd2dcc61ad45
		summarizeBy: none
		sourceColumn: Project ID

		annotation SummarizationSetBy = Automatic

	column 'Dataset Name'
		dataType: string
		lineageTag: 4539538a-8371-4f01-87a3-849757fd9ec1
		summarizeBy: none
		sourceColumn: Dataset Name

		annotation SummarizationSetBy = Automatic

	column role
		dataType: string
		lineageTag: 85e8dce8-4af1-4982-a8f5-d2d0182739ca
		summarizeBy: none
		sourceColumn: role

		annotation SummarizationSetBy = Automatic

	column 'Member Type'
		dataType: string
		lineageTag: 51a8d25d-b948-4551-9aed-328552f2ba0e
		summarizeBy: none
		sourceColumn: Member Type

		annotation SummarizationSetBy = Automatic

	column 'Member Email'
		dataType: string
		lineageTag: b09e96e2-df8b-45dd-8636-068cc3ffd24b
		summarizeBy: none
		sourceColumn: Member Email

		annotation SummarizationSetBy = Automatic

	column 'Condition.title'
		dataType: string
		lineageTag: 5af32f0d-db9b-48c0-b75f-bb2f65a07b8f
		summarizeBy: none
		sourceColumn: Condition.title

		annotation SummarizationSetBy = Automatic

	column 'Condition.expression'
		dataType: string
		lineageTag: 8a09b3b7-804a-4fdc-8cd0-092287cb220e
		summarizeBy: none
		sourceColumn: Condition.expression

		annotation SummarizationSetBy = Automatic

	partition 'fact_iam_policy (3)' = m
		mode: import
		source = ```
				let
				    // Query ini membaca file kebijakan IAM (dataset_policy.json) dari Google Cloud/BigQuery,
				    // mem-flatten struktur JSON bertingkat (policy > binding > condition), memisahkan
				    // Project ID dan Dataset Name dari path resource, memecah kondisi IAM (Condition.expression)
				    // menjadi 3 bagian (Expired Date, Type, Table/View Name), lalu meng-unpivot ketiga bagian
				    // tersebut menjadi baris terpisah untuk analisis per-kondisi. Hasil akhir difilter hanya
				    // baris yang memiliki Condition.title (kondisi IAM yang eksplisit diberi judul).
				
				    // Membaca dan mem-parsing file JSON kebijakan IAM dari path lokal
				    // ⚠️ RISIKO: Path file di-hardcode ke lokasi OneDrive milik satu user — query akan gagal
				    // total (file not found) jika dibuka oleh user lain atau di device lain
				    Source = Json.Document(File.Contents("C:\Users\stefanus.aditya\OneDrive - PT Pertamina (Persero)\Data Management FIles\IAM Dashboard\ai_subtep_test.json")),
				
				    // Menggabungkan seluruh list di dalam struktur JSON menjadi satu list datar
				    CombinedList = List.Combine(Source),
				
				    // Mengubah list hasil gabungan menjadi tabel dengan satu kolom
				    // ⚠️ RISIKO: ExtraValues.Error berarti jika ada baris dengan struktur tidak konsisten,
				    // query akan error keras (bukan silent) — ini sudah tepat untuk data governance, tapi
				    // pastikan sumber data selalu konsisten strukturnya
				    ConvertedToTable = Table.FromList(CombinedList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				
				    // Membuka record "policy" menjadi kolom-kolom terpisah
				    ExpandedColumn1 = Table.ExpandRecordColumn(ConvertedToTable, "Column1", {"policy"}, {"policy"}),
				
				    // Membuka record "policy" menjadi attachedResource dan binding
				    ExpandedPolicy = Table.ExpandRecordColumn(ExpandedColumn1, "policy", {"attachedResource", "binding"}, {"attachedResource", "binding"}),
				
				    // Membuka record "binding" menjadi role, members, dan condition
				    ExpandedBinding = Table.ExpandRecordColumn(ExpandedPolicy, "binding", {"role", "members", "condition"}, {"role", "members", "condition"}),
				
				    // Memecah list "members" menjadi satu baris per member
				    // ⚠️ RISIKO: Jika satu binding punya banyak member, jumlah baris akan bertambah signifikan
				    // (row explosion) — pastikan ini memang perilaku yang diinginkan
				    ExpandedMembers = Table.ExpandListColumn(ExpandedBinding, "members"),
				
				    // Membuka record "condition" menjadi kolom expression dan title
				    ExpandedCondition = Table.ExpandRecordColumn(ExpandedMembers, "condition", {"expression", "title"}, {"Condition.expression", "Condition.title"}),
				
				    // Mengambil teks path resource setelah kata kunci "/projects/"
				    ExtractAfterProject = Table.AddColumn(ExpandedCondition, "RawPath", each Text.AfterDelimiter([attachedResource], "/projects/")),
				
				    // Mengambil Project ID dari path (bagian sebelum "/datasets/", atau seluruh path jika project-level)
				    ExtractProjectID = Table.AddColumn(ExtractAfterProject, "Project ID", each Text.BeforeDelimiter([RawPath], "/datasets/", 0)),
				
				    // Mengambil Dataset Name jika path mengandung "/datasets/", jika tidak diberi label "N/A (Project Level)"
				    ExtractDataset = Table.AddColumn(ExtractProjectID, "Dataset Name", each 
				        if Text.Contains([RawPath], "/datasets/") 
				        then Text.AfterDelimiter([RawPath], "/datasets/") 
				        else "N/A (Project Level)"),
				
				    // Memisahkan tipe member (user/group/serviceAccount) dari bagian sebelum ":"
				    SplitMemberType = Table.AddColumn(ExtractDataset, "Member Type", each Text.BeforeDelimiter([members], ":")),
				
				    // Mengambil email member dari bagian setelah ":"
				    SplitMemberEmail = Table.AddColumn(SplitMemberType, "Member Email", each Text.AfterDelimiter([members], ":")),
				
				    // Memilih hanya kolom-kolom yang dibutuhkan untuk tahap berikutnya
				    // ⚠️ RISIKO: Jika salah satu nama kolom berikut tidak tersedia di sumber, step ini akan gagal
				    FinalTable = Table.SelectColumns(SplitMemberEmail,{"Project ID", "Dataset Name", "role", "Member Type", "Member Email", "Condition.title", "Condition.expression"}),
				
				    // Memisahkan baris Project Level (untuk proses dedup terpisah, karena Dataset Name selalu "N/A")
				    Filter_ProjectLevelRows = Table.SelectRows(FinalTable, each ([Dataset Name] = "N/A (Project Level)")),
				
				    // Memisahkan baris Dataset Level (untuk proses dedup terpisah)
				    Filter_DatasetLevelRows = Table.SelectRows(FinalTable, each [Dataset Name] <> "N/A (Project Level)"),
				
				    // Menghapus duplikat pada baris Project Level (kriteria: seluruh kolom kecuali Dataset Name yang sudah seragam)
				    // ⚠️ RISIKO: Table.Distinct membandingkan seluruh kolom di tabel — jika kolom Condition.expression
				    // berbeda redaksional tapi maknanya sama, baris akan dianggap unik (tidak ter-dedup)
				    DedupProjectLevel = Table.Distinct(
				        Filter_ProjectLevelRows
				    ),
				
				    // Menghapus duplikat pada baris Dataset Level
				    DedupDatasetLevel = Table.Distinct(
				        Filter_DatasetLevelRows
				    ),
				
				    // Menggabungkan kembali baris Project Level dan Dataset Level yang sudah di-dedup
				    Result = Table.Combine({DedupProjectLevel, DedupDatasetLevel}),
				
				    // Membersihkan karakter non-printable dari kolom Condition.expression
				    CleanedText = Table.TransformColumns(Result,{{"Condition.expression", Text.Clean, type text}})
				in
				    CleanedText
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

